### ISSUE TITLE
Protocol already defined

### ISSUE THREAD

**Issue by titolendable** [hoaproject/Protocol#8]
Every time I run a composer command, I am getting the following warning:

Warning: stream_wrapper_register(): Protocol hoa:// is already defined. in vendor/hoa/protocol/Wrapper.php on line 580

How can I avoid this warning? I did not register this package on composer, it is being used as a dependency to another package. The version in use is:

hoa/protocol                                    1.16.01.11            The Hoa\Protocol library.

**Comment by Hywan** [comment]
Hello :-),

Yes, some people has this trouble. This is because you still have `hoa/core` somewhere and your dependencie may not be updated correctly. Because of the BC break, some libraries still require old versions, I don't know exactly why Composer does this (this is not its fault, maybe its ours). Can I see you `composer.json` please?

**Comment by Hywan** [comment]
Duplicate https://github.com/hoaproject/Core/issues/90#issuecomment-171372679

**Comment by Hywan** [comment]
Please see https://github.com/hoaproject/Central/issues/32.

**Comment by shadowhand** [comment]
This is still a problem when using `composer update --prefer-lowest`, see failure here:

https://travis-ci.org/shadowhand/latitude/jobs/363503556#L613-L618

I am not sure what package(s) need to be version locked to prevent this error. The fact that Hoa does not use semver makes this even more difficult.
